#+TITLE: HW9
#+AUTHOR: Yusheng Zhao

* Problem 1
\begin{align}
& \sum_{k = 0}^{\delta} \eta(\tau - 1, k) \\
& = \sum_{k = 0}^{\delta} \frac{(\tau -1 + k)!}{(\tau -1)!k!} \\
& = \sum_{k = 0}^{\delta} \frac{(\tau -1 + k)!}{(\tau -1)!k!} \frac{(\tau +k)...(\tau + \delta)}{(\tau + k)...(\tau + \delta)} \frac{\tau (k+1)...\delta}{\tau (k+1)... \delta}\\
& = \frac{(\tau + \delta)!}{\tau! \delta!}\sum_{k = 0}^{\delta} \frac{\tau (k+1)...\delta}{(\tau +k)...(\tau + \delta)}
\end{align}

 Now, let's look at the summation in the last line. We could substitute $\tau
 =0$ into the summation and get $0$. Therefore, we could conclude that the
 polynomial expansion of the summation does not contain $\tau^-n$ terms, for $n
 > 1$. Let's assume $\sum_{k = 0}^{\delta} \frac{\tau (k+1)...\delta}{(\tau
 +k)...(\tau + \delta)} = poly(\tau)$ and then multiply both sides by $(\tau ) *
 ....*(\tau + \delta)$. We get,

 \begin{equation}
    \sum_{k=0}^{\delta} \tau * (k+1) * ... * \delta * \tau * ... * (\tau +k+1) = \tau * ...  *(\tau + \delta) * poly(\tau)
 \end{equation}

 We then compare the highest order term in $\tau$ on both sides. The l.h.s gives
 $\tau * \delta! * \frac{\tau^{\delta -1}}{\delta!} = \tau^\delta$. And the
 r.h.s gives $\tau^delta$ multilied by the leading order of $poly(\tau)$.
 Therefore, the leading order of $poly(\tau)$ must be $1$. Since $\poly(\tau)$
 does not contain $\tau^{-n}$ terms, $poly(\tau) = 1$.

 Therefore, we have reached the conclusion that $\sum_{k = 0}^{\delta}
 \frac{\tau (k+1)...\delta}{(\tau +k)...(\tau + \delta)} = 1$. Therefore,
 $\sum_{k = 0}^{\delta} \eta(\tau - 1, k) = \eta(\tau,\delta)$.
